CTFd/auth.py
import requests
from flask import Blueprint, abort
from flask import current_app as app
from flask import redirect, render_template, request, session, url_for
from flask_babel import lazy_gettext as _l

from CTFd.cache import cache, clear_team_session, clear_user_session
from CTFd.exceptions.email import (
    UserConfirmTokenInvalidException,
    UserResetPasswordTokenInvalidException,
)
from CTFd.models import Brackets, Teams, UserFieldEntries, UserFields, Users, db
from CTFd.utils import config, email, get_app_config, get_config
from CTFd.utils import user as current_user
from CTFd.utils import validators
from CTFd.utils.config import can_send_mail, is_teams_mode
from CTFd.utils.config.integrations import mlc_registration
from CTFd.utils.config.visibility import registration_visible
from CTFd.utils.crypto import verify_password
from CTFd.utils.decorators import ratelimit
from CTFd.utils.decorators.visibility import check_registration_visibility
from CTFd.utils.helpers import error_for, get_errors, markup
from CTFd.utils.logging import log
from CTFd.utils.modes import TEAMS_MODE
from CTFd.utils.security.auth import generate_preset_admin, login_user, logout_user
from CTFd.utils.security.email import (
    remove_email_confirm_token,
    remove_reset_password_token,
    verify_email_confirm_token,
    verify_reset_password_token,
)
from CTFd.utils.validators import ValidationError

auth = Blueprint("auth", __name__)


@auth.route("/confirm", methods=["POST", "GET"])
@auth.route("/confirm/<data>", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=60)
def confirm(data=None):
    # If we can't send mails our behavior depends on verify_emails
    if not can_send_mail():
        if get_config("verify_emails") is False:
            return redirect(url_for("challenges.listing"))
        else:
            return render_template(
                "confirm.html",
                errors=[
                    "Email verification is enabled but email sending isn't available. Please contact an admin to confirm your account"
                ],
            )

    # User is confirming email account
    if data and request.method == "GET":
        try:
            user_email = verify_email_confirm_token(data)
        except (UserConfirmTokenInvalidException):
            return render_template(
                "confirm.html",
                errors=["Your confirmation link is invalid, please generate a new one"],
            )

        user = Users.query.filter_by(email=user_email).first_or_404()
        if user.verified:
            return redirect(url_for("views.settings"))

        if (
            get_app_config("EMAIL_CONFIRMATION_REQUIRE_INTERACTION")
            and request.args.get("interaction") is None
        ):
            button = """<button style="margin-top: 3rem; padding: 1rem;" onclick="
                let u = new window.URL(window.location.href);
                u.searchParams.set('interaction', '1');
                window.location.href = u;">Click Here to Confirm Email</button>"""
            return render_template("page.html", content=button)

        user.verified = True
        log(
            "registrations",
            format="[{date}] {ip} - successful confirmation for {name}",
            name=user.name,
        )
        db.session.commit()
        remove_email_confirm_token(data)
        clear_user_session(user_id=user.id)
        # Only send this registration notification if we are preventing access to registered users only
        if get_config("verify_emails"):
            email.successful_registration_notification(user.email)
        db.session.close()
        if current_user.authed():
            return redirect(url_for("challenges.listing"))
        return redirect(url_for("auth.login"))

    # User is trying to start or restart the confirmation flow
    if current_user.authed() is False:
        return redirect(url_for("auth.login"))

    user = Users.query.filter_by(id=session["id"]).first_or_404()
    if user.verified:
        return redirect(url_for("views.settings"))

    if data is None:
        if request.method == "POST":
            # User wants to resend their confirmation email
            email.verify_email_address(user.email)
            log(
                "registrations",
                format="[{date}] {ip} - {name} initiated a confirmation email resend",
                name=user.name,
            )
            return render_template(
                "confirm.html", infos=[f"Confirmation email sent to {user.email}!"]
            )
        elif request.method == "GET":
            # User has been directed to the confirm page
            return render_template("confirm.html")


@auth.route("/reset_password", methods=["POST", "GET"])
@auth.route("/reset_password/<data>", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=60)
def reset_password(data=None):
    if config.can_send_mail() is False and data is None:
        return render_template(
            "reset_password.html",
            errors=[
                markup(
                    "This CTF is not configured to send email.<br> Please contact an organizer to have your password reset."
                )
            ],
        )

    if data is not None:
        try:
            email_address = verify_reset_password_token(data)
        except (UserResetPasswordTokenInvalidException):
            return render_template(
                "reset_password.html",
                errors=["Your reset link is invalid, please generate a new one"],
            )

        if request.method == "GET":
            return render_template("reset_password.html", mode="set")
        if request.method == "POST":
            password = request.form.get("password", "").strip()
            user = Users.query.filter_by(email=email_address).first_or_404()
            if user.oauth_id:
                return render_template(
                    "reset_password.html",
                    infos=[
                        "Your account was registered via an authentication provider and does not have an associated password. Please login via your authentication provider."
                    ],
                )

            pass_short = len(password) == 0
            if pass_short:
                return render_template(
                    "reset_password.html", errors=[_l("Please pick a longer password")]
                )

            password_min_length = int(get_config("password_min_length", default=0))
            pass_min = len(password) < password_min_length
            if pass_min:
                return render_template(
                    "reset_password.html",
                    errors=[
                        _l(
                            f"Password must be at least {password_min_length} characters"
                        )
                    ],
                )

            user.password = password
            user.change_password = False
            db.session.commit()
            remove_reset_password_token(data)
            clear_user_session(user_id=user.id)
            log(
                "logins",
                format="[{date}] {ip} - successful password reset for {name}",
                name=user.name,
            )
            db.session.close()
            email.password_change_alert(user.email)
            return redirect(url_for("auth.login"))

    if request.method == "POST":
        email_address = request.form["email"].strip()
        user = Users.query.filter_by(email=email_address).first()

        get_errors()

        if not user:
            return render_template(
                "reset_password.html",
                infos=[
                    _l(
                        "If that account exists you will receive an email, please check your inbox"
                    )
                ],
            )

        if user.oauth_id:
            return render_template(
                "reset_password.html",
                infos=[
                    _l(
                        "The email address associated with this account was registered via an authentication provider and does not have an associated password. Please login via your authentication provider."
                    )
                ],
            )

        # Preferably this would be in a pipeline or multi but the benefit is minor
        limit = cache.inc(f"reset_password_attempt_user_{user.id}")
        cache.expire(f"reset_password_attempt_user_{user.id}", 180)
        if limit > 5:
            return render_template(
                "reset_password.html",
                errors=[
                    _l("Too many password reset attempts. Please try again later.")
                ],
            )
        email.forgot_password(email_address)

        return render_template(
            "reset_password.html",
            infos=[
                _l(
                    "If that account exists you will receive an email, please check your inbox"
                )
            ],
        )
    return render_template("reset_password.html")


@auth.route("/register", methods=["POST", "GET"])
@check_registration_visibility
@ratelimit(method="POST", limit=10, interval=5)
def register():
    errors = get_errors()
    if current_user.authed():
        return redirect(url_for("challenges.listing"))

    num_users_limit = int(get_config("num_users", default=0))
    num_users = Users.query.filter_by(banned=False, hidden=False).count()
    if num_users_limit and num_users >= num_users_limit:
        abort(
            403,
            description=f"Reached the maximum number of users ({num_users_limit}).",
        )

    if request.method == "POST":
        name = request.form.get("name", "").strip()
        email_address = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "").strip()

        website = request.form.get("website")

CTFd/utils/challenges/__init__.py
import datetime
from collections import namedtuple

from sqlalchemy import func as sa_func
from sqlalchemy.sql import and_, false, true

from CTFd.cache import cache
from CTFd.models import Challenges, Ratings, Solves, Submissions, Users, db
from CTFd.schemas.submissions import SubmissionSchema
from CTFd.schemas.tags import TagSchema
from CTFd.utils import get_config
from CTFd.utils.dates import isoformat, unix_time_to_utc
from CTFd.utils.helpers.models import build_model_filters
from CTFd.utils.modes import generate_account_url, get_model

Challenge = namedtuple(
    "Challenge", ["id", "type", "name", "value", "category", "tags", "requirements"]
)

Rating = namedtuple("Rating", ["up", "down", "count"])


@cache.memoize(timeout=60)
def get_all_challenges(admin=False, field=None, q=None, **query_args):
    filters = build_model_filters(model=Challenges, query=q, field=field)
    chal_q = Challenges.query
    # Admins can see hidden and locked challenges in the admin view
    if admin is False:
        chal_q = chal_q.filter(
            and_(Challenges.state != "hidden", Challenges.state != "locked")
        )
    chal_q = (
        chal_q.filter_by(**query_args)
        .filter(*filters)
        .order_by(Challenges.value, Challenges.id)
    )
    tag_schema = TagSchema(view="user", many=True)

    results = []
    for c in chal_q:
        ct = Challenge(
            id=c.id,
            type=c.type,
            name=c.name,
            value=c.value,
            category=c.category,
            requirements=c.requirements,
            tags=tag_schema.dump(c.tags).data,
        )
        results.append(ct)
    return results


@cache.memoize(timeout=60)
def get_solves_for_challenge_id(challenge_id, freeze=False):
    Model = get_model()
    # Note that we specifically query for the Solves.account.name
    # attribute here because it is faster than having SQLAlchemy
    # query for the attribute directly and it's unknown what the
    # affects of changing the relationship lazy attribute would be
    solves = (
        Solves.query.add_columns(Model.name.label("account_name"))
        .join(Model, Solves.account_id == Model.id)
        .filter(
            Solves.challenge_id == challenge_id,
            Model.banned == False,
            Model.hidden == False,
        )
        .order_by(Solves.date.asc())
    )
    if freeze:
        freeze_time = get_config("freeze")
        if freeze_time:
            dt = datetime.datetime.utcfromtimestamp(freeze_time)
            solves = solves.filter(Solves.date < dt)
    results = []

    for solve in solves:
        # Seperate out the account name and the Solve object from the SQLAlchemy tuple
        solve, account_name = solve
        results.append(
            {
                "account_id": solve.account_id,
                "name": account_name,
                "date": isoformat(solve.date),
                "account_url": generate_account_url(account_id=solve.account_id),
            }
        )
    return results


@cache.memoize(timeout=60)
def get_submissions_for_user_id_for_challenge_id(user_id, challenge_id):
    user = Users.query.filter_by(id=user_id).first()
    submissions = (
        Submissions.query.join(Users)
        .filter(
            Submissions.challenge_id == challenge_id,
            Submissions.account_id == user.account_id,
        )
        .order_by(Submissions.date.desc())
    )
    response = SubmissionSchema(view="self", many=True).dump(submissions)
    return response


@cache.memoize(timeout=60)
def get_solve_ids_for_user_id(user_id):
    user = Users.query.filter_by(id=user_id).first()
    solve_ids = (
        Solves.query.with_entities(Solves.challenge_id)
        .filter(Solves.account_id == user.account_id)
        .all()
    )
    solve_ids = {value for value, in solve_ids}
    return solve_ids


@cache.memoize(timeout=60)
def get_solve_counts_for_challenges(challenge_id=None, admin=False):
    if challenge_id is None:
        challenge_id_filter = ()
    else:
        challenge_id_filter = (Solves.challenge_id == challenge_id,)
    AccountModel = get_model()
    freeze = get_config("freeze")
    if freeze and not admin:
        freeze_cond = Solves.date < unix_time_to_utc(freeze)
    else:
        freeze_cond = true()
    exclude_solves_cond = and_(
        AccountModel.banned == false(),
        AccountModel.hidden == false(),
    )
    solves_q = (
        db.session.query(
            Solves.challenge_id,
            sa_func.count(Solves.challenge_id),
        )
        .join(AccountModel)
        .filter(*challenge_id_filter, freeze_cond, exclude_solves_cond)
        .group_by(Solves.challenge_id)
    )

    solve_counts = {}
    for chal_id, solve_count in solves_q:
        solve_counts[chal_id] = solve_count
    return solve_counts


@cache.memoize(timeout=60)
def get_rating_average_for_challenge_id(challenge_id):
    ratings = Ratings.query.filter_by(challenge_id=challenge_id).all()

    if ratings:
        # Sum upvotes and downvotes
        up = 0
        down = 0
        count = 0
        for rating in ratings:
            count += 1
            if rating.value < 0:
                down += rating.value
            else:
                up += rating.value
        down = abs(down)
        return Rating(up=up, down=down, count=count)
    else:
        return Rating(up=0, down=0, count=0)

CTFd/utils/config/__init__.py
import os
import time

from flask import current_app as app

from CTFd.constants.themes import DEFAULT_THEME
from CTFd.utils import get_app_config, get_config
from CTFd.utils.modes import TEAMS_MODE, USERS_MODE


def ctf_name():
    name = get_config("ctf_name")
    return name if name else "CTFd"


def user_mode():
    return get_config("user_mode")


def is_users_mode():
    return user_mode() == USERS_MODE


def is_teams_mode():
    return user_mode() == TEAMS_MODE


def ctf_logo():
    return get_config("ctf_logo")


def ctf_theme():
    theme = get_config("ctf_theme")
    return theme if theme else ""


def ctf_theme_candidates():
    yield ctf_theme()
    if bool(get_app_config("THEME_FALLBACK")):
        yield DEFAULT_THEME


def is_setup():
    return bool(get_config("setup")) is True


def is_scoreboard_frozen():
    freeze = get_config("freeze")

    if freeze:
        freeze = int(freeze)
        if freeze < time.time():
            return True

    return False


def can_send_mail():
    return mailserver() or mailgun()


def get_mail_provider():
    mail_provider = app.config.get("MAIL_PROVIDER")
    if mail_provider:
        return mail_provider
    if get_config("mail_server") and get_config("mail_port"):
        return "smtp"
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return "mailgun"
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return "smtp"
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return "mailgun"


def mailgun():
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return True
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return True
    return False


def mailserver():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return True
    if get_config("mail_server") and get_config("mail_port"):
        return True
    return False


def get_themes():
    dir = os.path.join(app.root_path, "themes")
    return [
        name
        for name in os.listdir(dir)
        if os.path.isdir(os.path.join(dir, name)) and name != "admin"
    ]

CTFd/themes/core/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{{ title or Configs.ctf_name }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{{ Configs.ctf_small_icon }}" type="image/x-icon">

  {{ meta | safe }}

  {% block stylesheets %}
    {{ Assets.css("assets/scss/main.scss") }}
  {% endblock %}

  {{ Plugins.styles }}

  {{ Assets.js("assets/js/color_mode_switcher.js", type=None) }}

  <script type="text/javascript">
      window.init = {
          'urlRoot': "{{ request.script_root }}",
          'csrfNonce': "{{ Session.nonce }}",
          'userMode': "{{ Configs.user_mode }}",
          'userId': {{ Session.id }},
          'userName': {{ User.name | tojson }},
          'userEmail': {{ User.email | tojson }},
          'userVerified': {{ User.verified | tojson }},
          'teamId': {{ Team.id | tojson }},
          'teamName': {{ Team.name | tojson }},
          'start': {{ Configs.start | tojson }},
          'end': {{ Configs.end | tojson }},
          'themeSettings': {{ Configs.theme_settings | tojson }},
          'eventSounds': [
            "/themes/core/static/sounds/notification.webm",
            "/themes/core/static/sounds/notification.mp3",
          ],
      }
  </script>

  {{ Configs.theme_header }}
</head>
<body>
{% include "components/navbar.html" %}

<main role="main">
  {% block content %}
  {% endblock %}
</main>

{% include "components/snackbar.html" %}

<footer class="footer">
  <div class="container text-center">
    <a href="https://ctfd.io" class="text-secondary">
      <small class="text-muted">
        {% trans %}Powered by CTFd{% endtrans %}
      </small>
    </a>
  </div>
</footer>

{% include "components/notifications.html" %}

{% block scripts %}
  {{ Assets.js("assets/js/page.js") }}
{% endblock %}

{{ Plugins.scripts }}

{{ Configs.theme_footer }}
</body>
</html>

CTFd/themes/core/templates/challenges.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <div class="container">
      <h1>
        {% trans %}Challenges{% endtrans %}
      </h1>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {% include "components/errors.html" %}
      </div>
    </div>

    <div 
      x-data="ChallengeBoard" 
      @load-challenges.window="loadChallenges()" 
      @load-challenge.window="loadChallenge($event.detail)"
    >
      <div
          x-ref="challengeWindow" id="challenge-window" class="modal fade" tabindex="-1" role="dialog" x-data=""
          x-html="$store.challenge.data.view"
      ></div>

      <div x-show="!loaded">
        <div class="min-vh-50 d-flex align-items-center">
          <div class="text-center w-100">
            <i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
          </div>
        </div>
      </div>

      <div x-show="loaded">
        <template x-for="(category, idx) in getCategories()" :key="idx">
          <div class="pt-5">
            <div class="category-header mb-3">
              <h3 x-text="category"></h3>
            </div>

            <div class="category-challenges d-flex flex-column">
              <div class="challenges-row row">
                <template x-for="(c, idx) in getChallenges(category)" :key="c.id">
                  <div class="col-sm-6 col-md-4 col-lg-3 my-3">
                    <button
                        class="challenge-button btn btn-dark w-100 h-100"
                        :class="[
                          c.solved_by_me ? 'challenge-solved' : '',
                          ...c.tags.map((tag) => `tag-${tag.value.replace(/ /g, '-')}`),
                        ];"
                        :value="c.id" @click="loadChallenge(c.id)"
                    >

                      <div class="challenge-inner my-3">
                        <p x-text="c.name"></p>
                        <span x-text="c.value"></span>
                      </div>
                    </button>
                  </div>
                </template>
              </div>
            </div>
          </div>
        </template>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ Assets.js("assets/js/challenges.js") }}
{% endblock %}

CTFd/themes/core/templates/config.html
<form>
  <div class="form-group">
    <label>Challenge Window Size</label>
    <select class="form-control custom-select" name="challenge_window_size">
        <option value="sm">Small</option>
        <option value="norm">Normal</option>
        <option value="lg">Large</option>
        <option value="xl">Extra Large</option>
    </select>
  </div>

  <div class="form-group">
    <label>
      Challenge Category Order Custom Function<br>
      <small class="form-text text-muted">
        Define a <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description" target="_blank">custom compareFn function for Array.sort()</a> 
        used to sort the challenge categories
      </small>
    </label>
    <textarea class="form-control text-monospace" name="challenge_category_order" rows="5"></textarea>
  </div>

  <div class="form-group">
    <label>
      Challenge Order Custom Function<br>
      <small class="form-text text-muted">
        Define a <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description" target="_blank">custom compareFn function for Array.sort()</a> 
        used to sort the challenges within categories
      </small>
    </label>
    <textarea class="form-control text-monospace" name="challenge_order" rows="5"></textarea>
  </div>

  <div>
    <div class="form-check">
      <input type="checkbox" class="form-check-input" id="use_builtin_code_highlighter" name="use_builtin_code_highlighter" checked>
      <label class="form-check-label" for="use_builtin_code_highlighter">
        Use Built-In Syntax Highlighter
      </label>
    </div>
    <small class="form-text text-muted">
      The built-in syntax highlighter is lightweight and fast but may not always correctly highlight all languages. You can disable the built-in highlighter in order to use your own.
    </small>
  </div>

  <button type="submit" class="btn btn-primary float-right mt-4">Update</button>
</form>

CTFd/themes/core/templates/confirm.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <div class="container">
      <h1>
        {% trans %}Confirm{% endtrans %}
      </h1>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8 col-xl-6 offset-md-1 offset-lg-2 offset-xl-3">
        {% include "components/errors.html" %}

        {% if request.args.get('flow') == "init" %}
          <h5 class="text-center">
            {% trans %}To send a confirmation email to your email address, please click the button below.{% endtrans %}
          </h5>
          <br>
          <h5 class="text-center">
            {% trans %}Please click the link in that email to confirm your account.{% endtrans %}
          </h5>
          <h5 class="text-center">
            {% trans %}If the email doesn’t arrive, check your spam folder or contact an administrator to manually verify your account.{% endtrans %}
          </h5>
        {% else%}
          <h5 class="text-center">
            {% trans %}We've sent a confirmation email to your email address.{% endtrans %}
          </h5>
          <br>
          <h5 class="text-center">
            {% trans %}Please click the link in that email to confirm your account.{% endtrans %}
          </h5>
          <h5 class="text-center">
            {% trans %}If the email doesn’t arrive, check your spam folder or contact an administrator to manually verify your account.{% endtrans %}
          </h5>
        {% endif %}

        <hr>

        {% with form = Forms.auth.ConfirmForm() %}
          <form method="POST" action="{{ url_for('auth.confirm') }}">
            <div class="row">
              <div class="mb-3 col-md-6">
                {{ form.submit(class="btn btn-primary w-100 p-2") }}
              </div>
              <div class="mb-3 col-md-6">
                <a href="{{ url_for('views.settings') }}" class="btn btn-secondary w-100 p-2">
                  {% trans %}Change Email Address{% endtrans %}
                </a>
              </div>
              {{ form.nonce() }}
            </div>
          </form>
        {% endwith %}
      </div>
    </div>
  </div>
{% endblock %}

CTFd/themes/core/templates/login.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <div class="container">
      <h1>
        {% trans %}Login{% endtrans %}
      </h1>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-8 col offset-md-2 col-lg-6 offset-lg-3">
        {% include "components/errors.html" %}

        {% if integrations.mlc() %}
          <a class="btn btn-secondary btn-lg btn-block w-100" href="{{ url_for('auth.oauth_login') }}">
            Login with Major League Cyber
          </a>

          <hr>
        {% endif %}

        {% with form = Forms.auth.LoginForm() %}
          <form method="post" accept-charset="utf-8">
            <div class="mb-3">
              <b>{{ form.name.label(class="form-label") }}</b>
              {{ form.name(class="form-control", value=name, autocomplete="username email") }}
            </div>

            <div class="mb-3">
              <b>{{ form.password.label(class="form-label") }}</b>
              {{ form.password(class="form-control", value=password, autocomplete="current-password") }}
            </div>

            <div class="row pt-3">
              <div class="col-6 col-md-8">
                <a class="align-middle" href="{{ url_for('auth.reset_password') }}">
                  {% trans %}Forgot your password?{% endtrans %}
                </a>
              </div>

              <div class="col-6 col-md-4">
                {{ form.submit(class="btn btn-block btn-primary w-100") }}
              </div>
            </div>

            {{ form.nonce() }}
          </form>
        {% endwith %}
      </div>
    </div>
  </div>
{% endblock %}

CTFd/themes/core/templates/notifications.html
{% extends "base.html" %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>
				{% trans %}Notifications{% endtrans %}
			</h1>
		</div>
	</div>
	<div class="container">
		{% if not notifications %}
		<h2 class="text-center">
			{% trans %}There are no notifications yet{% endtrans %}
		</h2>
		{% endif %}
		{% for notification in notifications %}
		<div class="card bg-body-tertiary mb-4">
			<div class="card-body">
				<h3 class="card-title">{{ notification.title }}</h3>
				<blockquote class="blockquote mb-0">
					<p>{{ notification.html }}</p>
					<small class="text-muted"><span data-time="{{ notification.date | isoformat }}"></span></small>
				</blockquote>
			</div>
		</div>
		{% endfor %}
	</div>
{% endblock %}

{% block scripts %}
  {{ Assets.js("assets/js/notifications.js") }}
{% endblock %}

CTFd/themes/core/templates/page.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    {{ content | safe }}
  </div>
{% endblock %}

{% block scripts %}
  {{ Assets.js("assets/js/page.js") }}
{% endblock %}

CTFd/themes/core/templates/register.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <div class="container">
      <h1>
        {% trans %}Register{% endtrans %}
      </h1>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        {% include "components/errors.html" %}

        {% if integrations.mlc() %}
          <a class="btn btn-secondary btn-lg btn-block w-100" href="{{ url_for('auth.oauth_login') }}">
            Login with Major League Cyber
          </a>

          <hr>
        {% endif %}

        {% with form = Forms.auth.RegistrationForm() %}

          {% from "macros/forms.html" import render_extra_fields %}

          <form method="post" accept-charset="utf-8" role="form">

            <div class="mb-3">
              <b>{{ form.name.label(class="form-label") }}</b>
              {{ form.name(class="form-control", value=name, autocomplete="username") }}
              <small class="form-text text-muted">
                {% trans %}Your username on the site{% endtrans %}
              </small>
            </div>

            <div class="mb-3">
              <b>{{ form.email.label(class="form-label") }}</b>
              {{ form.email(class="form-control", value=email, autocomplete="email") }}
              <small class="form-text text-muted">
                {% trans %}Never shown to the public{% endtrans %}
              </small>
            </div>

            <div class="mb-3">
              <b>{{ form.password.label(class="form-label") }}</b>
              {{ form.password(class="form-control", value=password, autocomplete="new-password") }}
              <small class="form-text text-muted">
                {% trans %}Password used to log into your account{% endtrans %}
              </small>
            </div>

            {{ form.nonce() }}

            {{ render_extra_fields(form.extra) }}

            <div class="row pt-3">
              <div class="col-6 col-md-4 offset-6 offset-md-8">
                {{ form.submit(class="btn btn-block btn-primary w-100") }}
              </div>
            </div>

            {% if Configs.tos_or_privacy %}
              <div class="row pt-3">
                <div class="col-md-12 text-center">
                  <small class="text-muted text-center">
                    {% trans trimmed privacy_link=Configs.privacy_link, tos_link=Configs.tos_link %}
                    By registering, you agree to the
                    <a href="{{ privacy_link }}" target="_blank">privacy policy</a>
                    and <a href="{{ tos_link }}" target="_blank">terms of service</a>
                    {% endtrans %}
                  </small>
                </div>
              </div>
            {% endif %}
          </form>
        {% endwith %}
      </div>
    </div>
  </div>
{% endblock %}