CTFd/admin/__init__.py
import csv  # noqa: I001
import datetime
import os
from io import StringIO

from flask import Blueprint, abort
from flask import current_app as app
from flask import (
    jsonify,
    redirect,
    render_template,
    render_template_string,
    request,
    send_file,
    url_for,
)

admin = Blueprint("admin", __name__)

# isort:imports-firstparty
from CTFd.admin import challenges  # noqa: F401,I001
from CTFd.admin import notifications  # noqa: F401,I001
from CTFd.admin import pages  # noqa: F401,I001
from CTFd.admin import scoreboard  # noqa: F401,I001
from CTFd.admin import statistics  # noqa: F401,I001
from CTFd.admin import submissions  # noqa: F401,I001
from CTFd.admin import teams  # noqa: F401,I001
from CTFd.admin import users  # noqa: F401,I001
from CTFd.cache import (
    cache,
    clear_all_team_sessions,
    clear_all_user_sessions,
    clear_challenges,
    clear_config,
    clear_pages,
    clear_standings,
)
from CTFd.constants.setup import DEFAULTS
from CTFd.models import (
    Awards,
    Challenges,
    Configs,
    Notifications,
    Pages,
    Solves,
    Submissions,
    Teams,
    Tracking,
    Unlocks,
    Users,
    db,
)
from CTFd.utils import config as ctf_config
from CTFd.utils import get_app_config, get_config, set_config
from CTFd.utils.csv import dump_csv, load_challenges_csv, load_teams_csv, load_users_csv
from CTFd.utils.decorators import admins_only
from CTFd.utils.exports import background_import_ctf
from CTFd.utils.exports import export_ctf as export_ctf_util
from CTFd.utils.security.auth import logout_user
from CTFd.utils.uploads import delete_file
from CTFd.utils.user import is_admin


@admin.route("/admin", methods=["GET"])
def view():
    if is_admin():
        return redirect(url_for("admin.statistics"))
    return redirect(url_for("auth.login"))


@admin.route("/admin/plugins/<plugin>", methods=["GET", "POST"])
@admins_only
def plugin(plugin):
    if request.method == "GET":
        plugins_path = os.path.join(app.root_path, "plugins")

        config_html_plugins = [
            name
            for name in os.listdir(plugins_path)
            if os.path.isfile(os.path.join(plugins_path, name, "config.html"))
        ]

        if plugin in config_html_plugins:
            config_html = open(
                os.path.join(app.root_path, "plugins", plugin, "config.html")
            ).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == "POST":
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return "1"


@admin.route("/admin/import", methods=["GET", "POST"])
@admins_only
def import_ctf():
    if request.method == "GET":
        start_time = cache.get("import_start_time")
        end_time = cache.get("import_end_time")
        import_status = cache.get("import_status")
        import_error = cache.get("import_error")
        return render_template(
            "admin/import.html",
            start_time=start_time,
            end_time=end_time,
            import_status=import_status,
            import_error=import_error,
        )
    elif request.method == "POST":
        backup = request.files["backup"]
        background_import_ctf(backup)
        return redirect(url_for("admin.import_ctf"))


@admin.route("/admin/export", methods=["GET", "POST"])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d_%T")
    full_name = "{}.{}.zip".format(ctf_name, day)
    return send_file(
        backup, cache_timeout=-1, as_attachment=True, attachment_filename=full_name
    )


@admin.route("/admin/import/csv", methods=["POST"])
@admins_only
def import_csv():
    csv_type = request.form["csv_type"]
    # Try really hard to load data in properly no matter what nonsense Excel gave you
    raw = request.files["csv_file"].stream.read()
    try:
        csvdata = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        try:
            csvdata = raw.decode("cp1252")
        except UnicodeDecodeError:
            csvdata = raw.decode("latin-1")
    csvfile = StringIO(csvdata)

    loaders = {
        "challenges": load_challenges_csv,
        "users": load_users_csv,
        "teams": load_teams_csv,
    }

    loader = loaders[csv_type]
    reader = csv.DictReader(csvfile)
    success = loader(reader)
    if success is True:
        return redirect(url_for("admin.config"))
    else:
        return jsonify(success), 500


@admin.route("/admin/export/csv")
@admins_only
def export_csv():
    table = request.args.get("table")

    output = dump_csv(name=table)

    return send_file(
        output,
        as_attachment=True,
        max_age=-1,
        download_name="{name}-{table}.csv".format(
            name=ctf_config.ctf_name(), table=table
        ),
    )


@admin.route("/admin/config", methods=["GET", "POST"])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    configs = Configs.query.all()
    configs = {c.key: get_config(c.key) for c in configs}

    # Load in defaults that would normally exist on UI setup
    for k, v in DEFAULTS.items():
        if k not in configs:
            configs[k] = v

    themes = ctf_config.get_themes()

    # Remove current theme but ignore failure
    try:
        themes.remove(get_config("ctf_theme"))
    except ValueError:
        pass

    force_html_sanitization = get_app_config("HTML_SANITIZATION")

    return render_template(
        "admin/config.html",
        themes=themes,
        **configs,
        force_html_sanitization=force_html_sanitization
    )


@admin.route("/admin/reset", methods=["GET", "POST"])
@admins_only
def reset():
    if request.method == "POST":
        require_setup = False
        logout = False
        next_url = url_for("admin.statistics")

        data = request.form

        if data.get("pages"):
            _pages = Pages.query.all()
            for p in _pages:
                for f in p.files:
                    delete_file(file_id=f.id)

            Pages.query.delete()

        if data.get("notifications"):
            Notifications.query.delete()

        if data.get("challenges"):
            _challenges = Challenges.query.all()
            for c in _challenges:
                for f in c.files:
                    delete_file(file_id=f.id)
            Challenges.query.delete()

        if data.get("accounts"):
            Users.query.delete()
            Teams.query.delete()
            require_setup = True
            logout = True

        if data.get("submissions"):
            Solves.query.delete()
            Submissions.query.delete()
            Awards.query.delete()
            Unlocks.query.delete()
            Tracking.query.delete()

        if data.get("user_mode") == "users":
            db.session.query(Users).update({Users.team_id: None})
            Teams.query.delete()

            clear_all_user_sessions()
            clear_all_team_sessions()

        if require_setup:
            set_config("setup", False)
            cache.clear()
            logout_user()
            next_url = url_for("views.setup")

        db.session.commit()

        clear_pages()
        clear_standings()
        clear_challenges()
        clear_config()

        if logout is True:
            cache.clear()
            logout_user()

        db.session.close()
        return redirect(next_url)

    return render_template("admin/reset.html")

CTFd/auth.py
import requests
from flask import Blueprint, abort
from flask import current_app as app
from flask import redirect, render_template, request, session, url_for
from flask_babel import lazy_gettext as _l

from CTFd.cache import cache, clear_team_session, clear_user_session
from CTFd.exceptions.email import (
    UserConfirmTokenInvalidException,
    UserResetPasswordTokenInvalidException,
)
from CTFd.models import Brackets, Teams, UserFieldEntries, UserFields, Users, db
from CTFd.utils import config, email, get_app_config, get_config
from CTFd.utils import user as current_user
from CTFd.utils import validators
from CTFd.utils.config import can_send_mail, is_teams_mode
from CTFd.utils.config.integrations import mlc_registration
from CTFd.utils.config.visibility import registration_visible
from CTFd.utils.crypto import verify_password
from CTFd.utils.decorators import ratelimit
from CTFd.utils.decorators.visibility import check_registration_visibility
from CTFd.utils.helpers import error_for, get_errors, markup
from CTFd.utils.logging import log
from CTFd.utils.modes import TEAMS_MODE
from CTFd.utils.security.auth import generate_preset_admin, login_user, logout_user
from CTFd.utils.security.email import (
    remove_email_confirm_token,
    remove_reset_password_token,
    verify_email_confirm_token,
    verify_reset_password_token,
)
from CTFd.utils.validators import ValidationError

auth = Blueprint("auth", __name__)


@auth.route("/confirm", methods=["POST", "GET"])
@auth.route("/confirm/<data>", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=60)
def confirm(data=None):
    # If we can't send mails our behavior depends on verify_emails
    if not can_send_mail():
        if get_config("verify_emails") is False:
            return redirect(url_for("challenges.listing"))
        else:
            return render_template(
                "confirm.html",
                errors=[
                    "Email verification is enabled but email sending isn't available. Please contact an admin to confirm your account"
                ],
            )

    # User is confirming email account
    if data and request.method == "GET":
        try:
            user_email = verify_email_confirm_token(data)
        except (UserConfirmTokenInvalidException):
            return render_template(
                "confirm.html",
                errors=["Your confirmation link is invalid, please generate a new one"],
            )

        user = Users.query.filter_by(email=user_email).first_or_404()
        if user.verified:
            return redirect(url_for("views.settings"))

        if (
            get_app_config("EMAIL_CONFIRMATION_REQUIRE_INTERACTION")
            and request.args.get("interaction") is None
        ):
            button = """<button style="margin-top: 3rem; padding: 1rem;" onclick="
                let u = new window.URL(window.location.href);
                u.searchParams.set('interaction', '1');
                window.location.href = u;">Click Here to Confirm Email</button>"""
            return render_template("page.html", content=button)

        user.verified = True
        log(
            "registrations",
            format="[{date}] {ip} - successful confirmation for {name}",
            name=user.name,
        )
        db.session.commit()
        remove_email_confirm_token(data)
        clear_user_session(user_id=user.id)
        # Only send this registration notification if we are preventing access to registered users only
        if get_config("verify_emails"):
            email.successful_registration_notification(user.email)
        db.session.close()
        if current_user.authed():
            return redirect(url_for("challenges.listing"))
        return redirect(url_for("auth.login"))

    # User is trying to start or restart the confirmation flow
    if current_user.authed() is False:
        return redirect(url_for("auth.login"))

    user = Users.query.filter_by(id=session["id"]).first_or_404()
    if user.verified:
        return redirect(url_for("views.settings"))

    if data is None:
        if request.method == "POST":
            # User wants to resend their confirmation email
            email.verify_email_address(user.email)
            log(
                "registrations",
                format="[{date}] {ip} - {name} initiated a confirmation email resend",
                name=user.name,
            )
            return render_template(
                "confirm.html", infos=[f"Confirmation email sent to {user.email}!"]
            )
        elif request.method == "GET":
            # User has been directed to the confirm page
            return render_template("confirm.html")


@auth.route("/reset_password", methods=["POST", "GET"])
@auth.route("/reset_password/<data>", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=60)
def reset_password(data=None):
    if config.can_send_mail() is False and data is None:
        return render_template(
            "reset_password.html",
            errors=[
                markup(
                    "This CTF is not configured to send email.<br> Please contact an organizer to have your password reset."
                )
            ],
        )

    if data is not None:
        try:
            email_address = verify_reset_password_token(data)
        except (UserResetPasswordTokenInvalidException):
            return render_template(
                "reset_password.html",
                errors=["Your reset link is invalid, please generate a new one"],
            )

        if request.method == "GET":
            return render_template("reset_password.html", mode="set")
        if request.method == "POST":
            password = request.form.get("password", "").strip()
            user = Users.query.filter_by(email=email_address).first_or_404()
            if user.oauth_id:
                return render_template(
                    "reset_password.html",
                    infos=[
                        "Your account was registered via an authentication provider and does not have an associated password. Please login via your authentication provider."
                    ],
                )

            pass_short = len(password) == 0
            if pass_short:
                return render_template(
                    "reset_password.html", errors=[_l("Please pick a longer password")]
                )

            password_min_length = int(get_config("password_min_length", default=0))
            pass_min = len(password) < password_min_length
            if pass_min:
                return render_template(
                    "reset_password.html",
                    errors=[
                        _l(
                            f"Password must be at least {password_min_length} characters"
                        )
                    ],
                )

            user.password = password
            user.change_password = False
            db.session.commit()
            remove_reset_password_token(data)
            clear_user_session(user_id=user.id)
            log(
                "logins",
                format="[{date}] {ip} - successful password reset for {name}",
                name=user.name,
            )
            db.session.close()
            email.password_change_alert(user.email)
            return redirect(url_for("auth.login"))

    if request.method == "POST":
        email_address = request.form["email"].strip()
        user = Users.query.filter_by(email=email_address).first()

        get_errors()

        if not user:
            return render_template(
                "reset_password.html",
                infos=[
                    _l(
                        "If that account exists you will receive an email, please check your inbox"
                    )
                ],
            )

        if user.oauth_id:
            return render_template(
                "reset_password.html",
                infos=[
                    _l(
                        "The email address associated with this account was registered via an authentication provider and does not have an associated password. Please login via your authentication provider."
                    )
                ],
            )

        # Preferably this would be in a pipeline or multi but the benefit is minor
        limit = cache.inc(f"reset_password_attempt_user_{user.id}")
        cache.expire(f"reset_password_attempt_user_{user.id}", 180)
        if limit > 5:
            return render_template(
                "reset_password.html",
                errors=[
                    _l("Too many password reset attempts. Please try again later.")
                ],
            )
        email.forgot_password(email_address)

        return render_template(
            "reset_password.html",
            infos=[
                _l(
                    "If that account exists you will receive an email, please check your inbox"
                )
            ],
        )
    return render_template("reset_password.html")


@auth.route("/register", methods=["POST", "GET"])
@check_registration_visibility
@ratelimit(method="POST", limit=10, interval=5)
def register():
    errors = get_errors()
    if current_user.authed():
        return redirect(url_for("challenges.listing"))

    num_users_limit = int(get_config("num_users", default=0))
    num_users = Users.query.filter_by(banned=False, hidden=False).count()
    if num_users_limit and num_users >= num_users_limit:
        abort(
            403,
            description=f"Reached the maximum number of users ({num_users_limit}).",
        )

    if request.method == "POST":
        name = request.form.get("name", "").strip()
        email_address = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "").strip()

        website = request.form.get("website")

CTFd/themes/core/templates/components/errors.html
<div>
  {% for info in infos %}
    <div class="alert alert-info alert-dismissible text-center" role="alert">
      <span>{{ info }}</span>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true"></span>
      </button>
    </div>
  {% endfor %}

  {% for error in errors %}
    <div class="alert alert-danger alert-dismissible text-center" role="alert">
      <span>{{ error }}</span>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true"></span>
      </button>
    </div>
  {% endfor %}
</div>

CTFd/themes/core/templates/components/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container">
    <a href="{{ url_for('views.static_html', route='/') }}" class="navbar-brand">
      {% if Configs.ctf_logo %}
        <img
            class="img-responsive ctf_logo"
            src="{{ url_for('views.files', path=Configs.ctf_logo) }}"
            alt="{{ Configs.ctf_name }}"
            height="25"
        >
      {% else %}
        {{ Configs.ctf_name }}
      {% endif %}
    </a>

    <button
        class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#base-navbars"
        aria-controls="base-navbars" aria-expanded="false" aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="base-navbars">
      <ul class="navbar-nav me-auto">
        {% for page in Plugins.user_menu_pages %}
          <li class="nav-item">
            <a class="nav-link" href="{{ page.route }}" {% if page.link_target %}target="{{ page.link_target }}"{% endif %}>
              {{ page.title }}
            </a>
          </li>
        {% endfor %}

        {% if Configs.account_visibility != 'admins' %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.listing') }}">
              {% trans %}Users{% endtrans %}
            </a>
          </li>

          {% if Configs.user_mode == 'teams' %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('teams.listing') }}">
                {% trans %}Teams{% endtrans %}
              </a>
            </li>
          {% endif %}
        {% endif %}

        {% if Configs.account_visibility != 'admins' and Configs.score_visibility != 'admins' %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('scoreboard.listing') }}">
              {% trans %}Scoreboard{% endtrans %}
            </a>
          </li>
        {% endif %}

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('challenges.listing') }}">
            {% trans %}Challenges{% endtrans %}
          </a>
        </li>
      </ul>

      <hr class="d-sm-flex d-md-flex d-lg-none">

      <ul class="navbar-nav ms-md-auto d-block d-sm-flex d-md-flex">
        {% if authed() %}

          {% if is_admin() %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.view') }}">
                <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans %}Admin Panel{% endtrans %}">
                    <i class="fas fa-wrench d-none d-md-inline d-lg-none"></i>
                </span>
                <span class="d-sm-inline d-md-none d-lg-inline">
                  <i class="fas fa-wrench pe-1"></i>
                  {% trans %}Admin Panel{% endtrans %}
                </span>
              </a>
            </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('views.notifications') }}">
              <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans %}Notifications{% endtrans %}">
                <i class="fas fa-bell d-none d-md-inline d-lg-none"></i>
              </span>
              <span class="d-sm-inline d-md-none d-lg-inline">
                  <i class="fas fa-bell pe-1"></i>
                  <span x-data x-show="$store.unread_count > 0" x-text="$store.unread_count" class="badge rounded-pill bg-danger badge-notification"></span>
                  {% trans %}Notifications{% endtrans %}
              </span>
            </a>
          </li>

          {% if Configs.user_mode == "teams" %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('teams.private') }}">
                <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans %}Team{% endtrans %}">
                  <i class="fas fa-users d-none d-md-inline d-lg-none"></i>
                </span>
                <span class="d-sm-inline d-md-none d-lg-inline">
                  <i class="fas fa-users pe-1"></i>
                  {% trans %}Team{% endtrans %}
                </span>
              </a>
            </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.private') }}">
              <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans %}Profile{% endtrans %}">
                <i class="fas fa-user-circle d-none d-md-inline d-lg-none"></i>
              </span>
              <span class="d-sm-inline d-md-none d-lg-inline">
                <i class="fas fa-user-circle pe-1"></i>
                {% trans %}Profile{% endtrans %}
              </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('views.settings') }}">
              <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans %}Settings{% endtrans %}">
                <i class="fas fa-cogs d-none d-md-inline d-lg-none"></i>
              </span>
              <span class="d-sm-inline d-md-none d-lg-inline">
                <i class="fas fa-cogs pe-1"></i>
                {% trans %}Settings{% endtrans %}
              </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">
              <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans %}Logout{% endtrans %}">
                <i class="fas fa-sign-out-alt d-none d-md-inline d-lg-none"></i>
              </span>
              <span class="d-sm-inline d-md-none d-lg-inline">
                <i class="fas fa-sign-out-alt pe-1"></i><span class="d-lg-none">
                  {% trans %}Logout{% endtrans %}
                </span>
              </span>
            </a>
          </li>
        {% else %}

          {% if registration_visible() %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.register') }}">
                <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans %}Register{% endtrans %}">
                  <i class="fas fa-user-plus d-none d-md-inline d-lg-none"></i>
                </span>
                <span class="d-sm-inline d-md-none d-lg-inline">
                  <i class="fas fa-user-plus pe-1"></i>
                  {% trans %}Register{% endtrans %}
                </span>
              </a>
            </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">
              <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans %}Login{% endtrans %}">
                <i class="fas fa-sign-in-alt d-none d-md-inline d-lg-none"></i>
              </span>
              <span class="d-sm-inline d-md-none d-lg-inline">
                <i class="fas fa-sign-in-alt pe-1"></i>
                {% trans %}Login{% endtrans %}
              </span>
            </a>
          </li>
        {% endif %}

        <li class="nav-item dropdown">
          <button class="nav-link dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-language d-none d-md-inline"></i>
            <span class="d-sm-inline d-md-none">
              <i class="fas fa-language pe-1"></i>
              {% trans %}Change language{% endtrans %}
            </span>
          </button>
          <form x-data="LanguageForm">
            <ul class="dropdown-menu dropdown-menu-end">
              {% set curr_lang = get_locale() %}
              {%- for lang in Languages.names.items() %}
              <li>
                  <span class="dropdown-item {{ 'bg-primary text-white' if (curr_lang == lang[0]) }}" @click="set" value="{{ lang[0] }}">
                    {{ lang[1] }}
                  </span>
              </li>
              {%- endfor %}
            </ul>
          </form>
        </li>

        <li class="nav-item">
          <button class="nav-link theme-switch" type="button">
            <span data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans %}Toggle theme{% endtrans %}">
              <i class="fas fa-sun d-none d-md-inline"></i>
            </span>
            <span class="d-sm-inline d-md-none">
              <i class="fas fa-sun pe-1"></i>
              {% trans %}Toggle theme{% endtrans %}
            </span>
          </button>
        </li>
      </ul>
    </div>
  </div>
</nav>

CTFd/themes/core/templates/components/notifications.html
<div x-data>
  <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
    <div x-ref="toast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="false">
      <div class="toast-header">
        <strong class="me-auto" x-text="$store.toast.title"></strong>
        <small>just now</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body" x-html="$store.toast.html">
      </div>
    </div>
  </div>
</div>


<div x-data>
  <div class="modal fade" x-ref="modal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" x-text="$store.modal.title"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p x-html="$store.modal.html"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Got it!</button>
        </div>
      </div>
    </div>
  </div>
</div>

CTFd/themes/core/templates/components/snackbar.html
{% if can_send_mail() %}
<div 
    id="ctfdio-snackbar-email-nudge"
    x-data 
    x-show="window.init.userId && !window.init.userVerified && localStorage.getItem('remind_email_verify') != window.init.userId && (!['/team', '/teams/join', '/teams/new'].includes(window.location.pathname) || window.init.teamId != null)"
    class="alert alert-info alert-dismissible col-md-4 col-10 position-fixed text-center m-0 ctfdio-email-nudge" 
    style="bottom: 45px; left: 50%; transform: translateX(-50%); z-index: 1040; display: none;" 
    role="alert"
>
  <small>
    <strong>Email Unconfirmed</strong><br>
    <span>To confirm your email address please <a href="{{ url_for('auth.confirm', flow='init') }}">click here</a>.</span>
  </small>
  <button type="button" class="btn-close" @click="localStorage.setItem('remind_email_verify', window.init.userId); $el.parentElement.style.display = 'none';" aria-label="Close"></button>
</div>
{% endif %}